image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - staging
  - prod

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  only: hhpm_dev_1.0
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY

prod:
  type: deploy
  stage: prod
  image: ruby:latest
  only: hhpm_prod_1.0
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
