image: node:16.14.2

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - tests
  - staging
  - prod

tests:
  type: tests
  stage: tests
  only:
    - /^preprod_[0-9]+(?:.[0-9]+)+$/
  image: weboaks/node-karma-protractor-chrome
  script:
    - npm install --silent
    - npm run test

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  only:
    - /^preprod_[0-9]+(?:.[0-9]+)+$/
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY

prod:
  type: deploy
  stage: prod
  image: ruby:latest
  only:
    - /^prod_[0-9]+(?:.[0-9]+)+$/
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING_PROD --api-key=$HEROKU_API_KEY
