name: TestLOPES

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: tests
        run: npm run test
