name: ContinuousIntegrationBuild

on:
  push:
    branches:
      - feat_mb-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: installation dependencies
        run: npm install
  heroku-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "calculatricedufutur"
          heroku_email: "meryg.beguet@gmail.com"
          dontuseforce: 1
          justlogin: true
      - name: "Login to heroku registry"
        run: heroku container:login
      - name: "Build and push to heroku registry"
        run: heroku container:push feat_mb-1 --app calculatricedufutur
      - name: "Releases the container"
        run: heroku container:release feat_mb-1 --app calculatricedufutur
