name: ContinuousIntegrationBuild

on:
  push:
    branches:
      - feat_mb-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: installation dependencies
        run: npm install
  heroku-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1

      - name: Add api remote origin
        run: |
          git remote add heroku-api https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/calculatricedufutur.git
      - name: Deploy api to Heroku
        run: |
          git subtree push --prefix server heroku-api master
      - name: Add frontend remote origin
        run: |
          git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/caculatricedufutur.git
      - name: Deploy frontend to Heroku
        run: |
          git subtree push --prefix frontend heroku-frontend master
