name: ContinuousIntegrationBuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: installation dependencies
        run: npm install
      - name: App build
        run: npm run build
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Add remote origin
      run: |
            git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/calclatricedufutur.git
            - name: Deploy to Heroku
              run: |
                git push heroku HEAD:master -f



