name: ContinuousIntegrationBuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: installation dependencies
        run: npm install
        env:
          CI: true
      - name: App build
        run: npm run build

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build